=== abuob/yanice/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "schemaVersion": {
            "type": "number"
        },
        "options": {
            "$ref": "#options"
        },
        "plugins": {
            "type": "object",
            "properties": {
                "officiallySupported": {
                    "type": "object",
                    "properties": {
                        "import-boundaries": {
                            "type": "object",
                            "properties": {
                                "importResolvers": {
                                    "type": "object",
                                    "description": "A map of glob-expressions to an array of import resolvers. Matching files will have those resolvers applied.",
                                    "patternProperties": {
                                        "^.+$": {
                                            "type": "array",
                                            "items": {
                                                "type": "string"
                                            }
                                        }
                                    }
                                },
                                "postResolve": {
                                    "description": "List of path to scripts (relative to yanice.json) that allow to resolve imports further; e.g. to resolve typescript-path-mappings that the built-in 'es6-declarative-import-resolver' cannot resolve itself. See documentation for expected format.",
                                    "type": "array",
                                    "items": {
                                        "type": "string"
                                    }
                                },
                                "assertions": {
                                    "type": "array",
                                    "items": {
                                        "enum": [
                                            "only-direct-imports",
                                            "only-transitive-dependencies",
                                            "use-all-declared-dependencies",
                                            "max-skipped-imports",
                                            "access-via-entrypoints",
                                            "restrict-package-imports",
                                            "no-circular-imports"
                                        ]
                                    }
                                },
                                "customAssertions": {
                                    "type": "array",
                                    "description": "Paths relative to scripts containing an assertion",
                                    "items": {
                                        "type": "string"
                                    }
                                },
                                "assertionOptions": {
                                    "type": "object",
                                    "properties": {
                                        "skippedImports": {
                                            "type": "object",
                                            "properties": {
                                                "mode": {
                                                    "enum": ["exact", "max"]
                                                },
                                                "amount": {
                                                    "type": "number"
                                                }
                                            },
                                            "required": ["mode", "amount"],
                                            "additionalProperties": false
                                        },
                                        "ignoredProjects": {
                                            "description": "These projects are not considered for the sake of boundary-assertions. This is especially useful for pseudo-projects like 'ALL-TYPESCRIPT-FILES' and such, as import-boundary-assertions would be meaningless for them.",
                                            "type": "array",
                                            "items": {
                                                "type": "string"
                                            }
                                        },
                                        "accessViaEntryPoints": {
                                            "type": "object",
                                            "properties": {
                                                "allowWithinSameProject": {
                                                    "type": "boolean"
                                                }
                                            },
                                            "required": ["allowWithinSameProject"],
                                            "additionalProperties": false
                                        },
                                        "restrictPackageImports": {
                                            "description": "Any package can either be allowed (with exceptions) or blocked (with exceptions). A boolean flag controls whether this needs to be explicitly done for all packages.",
                                            "type": "object",
                                            "properties": {
                                                "allPackagesMustBeListed": {
                                                    "description": "If set to true, a package-import must either be allowed or blocked by default. If false, it is implicitly allowed.",
                                                    "type": "boolean"
                                                },
                                                "allowConfiguration": {
                                                    "type": "object",
                                                    "properties": {
                                                        "allowByDefault": {
                                                            "description": "List of packages that are allowed by default.",
                                                            "type": "array",
                                                            "items": {
                                                                "type": "string"
                                                            }
                                                        },
                                                        "exceptions": {
                                                            "description": "Map of projects (keys) to arrays (values) to control where we want to block projects which are otherwise allowed by default.",
                                                            "type": "object",
                                                            "patternProperties": {
                                                                "^[a-zA-Z][0-9a-zA-Z-]*$": {
                                                                    "type": "array",
                                                                    "items": {
                                                                        "type": "string"
                                                                    }
                                                                }
                                                            },
                                                            "additionalProperties": false
                                                        }
                                                    },
                                                    "required": ["allowByDefault"],
                                                    "additionalProperties": false
                                                },
                                                "blockConfiguration": {
                                                    "type": "object",
                                                    "properties": {
                                                        "blockByDefault": {
                                                            "description": "List of packages that are blocked by default.",
                                                            "type": "array",
                                                            "items": {
                                                                "type": "string"
                                                            }
                                                        },
                                                        "exceptions": {
                                                            "description": "Map of projects (keys) to arrays (values) to control where we want to allow projects which are otherwise blocked by default.",
                                                            "type": "object",
                                                            "patternProperties": {
                                                                "^[a-zA-Z][0-9a-zA-Z-]*$": {
                                                                    "type": "array",
                                                                    "items": {
                                                                        "type": "string"
                                                                    }
                                                                }
                                                            },
                                                            "additionalProperties": false
                                                        }
                                                    },
                                                    "required": ["blockByDefault"],
                                                    "additionalProperties": false
                                                }
                                            },
                                            "additionalProperties": false
                                        },
                                        "noCircularImports": {
                                            "type": "object",
                                            "properties": {
                                                "excludedProjects": {
                                                    "description": "Any file that is part of any of the listed projects will not be included in the circular import check.",
                                                    "type": "array",
                                                    "items": {
                                                        "type": "string"
                                                    }
                                                }
                                            },
                                            "additionalProperties": false
                                        }
                                    },
                                    "additionalProperties": false
                                }
                            },
                            "additionalProperties": false,
                            "required": ["importResolvers"]
                        }
                    }
                },
                "custom": {
                    "type": "object",
                    "patternProperties": {
                        "^[a-zA-Z][0-9a-zA-Z-]*$": {
                            "type": "object",
                            "properties": {
                                "scriptLocation": {
                                    "type": "string"
                                }
                            },
                            "additionalProperties": true,
                            "required": ["scriptLocation"]
                        }
                    }
                }
            }
        },
        "projects": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "projectName": {
                        "$ref": "#projectNamePatternString"
                    },
                    "projectFolder": {
                        "type": "string"
                    },
                    "pathGlob": {
                        "type": "string"
                    },
                    "pathRegExp": {
                        "type": "string"
                    },
                    "commands": {
                        "$ref": "#commands"
                    },
                    "responsibles": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "entrypoints": {
                        "type": "array",
                        "description": "Only relevant for the access-via-entrypoints assertion of the @yanice/import-boundaries plugin",
                        "items": {
                            "type": "string"
                        }
                    }
                },
                "required": ["projectName"],
                "additionalProperties": false
            }
        },
        "dependencyScopes": {
            "type": "object",
            "patternProperties": {
                "^[a-zA-Z][0-9a-zA-Z-]*$": {
                    "type": "object",
                    "properties": {
                        "defaultDependencies": {
                            "type": "array",
                            "items": {
                                "$ref": "#projectNamePatternString"
                            }
                        },
                        "extends": {
                            "$ref": "#projectNamePatternString"
                        },
                        "dependencies": {
                            "$ref": "#dependencies"
                        },
                        "options": {
                            "$ref": "#options"
                        }
                    },
                    "required": ["dependencies"],
                    "additionalProperties": false
                }
            },
            "additionalProperties": false
        }
    },
    "required": ["schemaVersion", "projects", "dependencyScopes"],
    "definitions": {
        "projectNamePatternString": {
            "$id": "#projectNamePatternString",
            "type": "string",
            "pattern": "^[a-zA-Z][0-9a-zA-Z-]*$"
        },
        "commands": {
            "$id": "#commands",
            "type": "object",
            "patternProperties": {
                "^[a-zA-Z][0-9a-zA-Z-]*$": {
                    "type": "object",
                    "properties": {
                        "command": {
                            "type": "string"
                        },
                        "cwd": {
                            "type": "string"
                        },
                        "commands": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "oneOf": [{ "required": ["command"] }, { "required": ["commands"] }],
                    "additionalProperties": false
                }
            }
        },
        "options": {
            "$id": "#options",
            "type": "object",
            "properties": {
                "commandOutput": {
                    "enum": ["ignore", "append-at-end", "append-at-end-on-error"]
                },
                "outputFilters": {
                    "type": "array",
                    "items": {
                        "enum": ["npmError", "karmaProgressSuccess", "ignoreStderr", "ignoreStdout"]
                    }
                },
                "outputFolder": {
                    "type": "string"
                },
                "port": {
                    "type": "number"
                }
            },
            "additionalProperties": false
        },
        "dependencies": {
            "$id": "#dependencies",
            "type": "object",
            "patternProperties": {
                "^[a-zA-Z][0-9a-zA-Z-]*$": {
                    "type": "array",
                    "items": {
                        "$ref": "#projectNamePatternString"
                    }
                }
            },
            "additionalProperties": false
        }
    }
}

=== abuob/yanice/src/__fixtures/valid-3.yanice.json
{
  "$schema": "../../schema.json",
  "schemaVersion": 2,
  "options": {
    "commandOutput": "append-at-end",
    "outputFilters": ["npmError"],
    "outputFolder": "./.yanice-graph-output",
    "port": 7777
  },
  "projects": [
    {
      "projectName": "project-A",
      "pathRegExp": "project-A",
      "pathGlob": "project-A/**"
    },
    {
      "projectName": "project-B",
      "pathRegExp": "project-B"
    },
    {
      "projectName": "lib-1",
      "pathRegExp": "libs/lib-1"
    },
    {
      "projectName": "lib-2",
      "pathRegExp": "libs/lib-2"
    }
  ],
  "dependencyScopes": {
    "test": {
      "options": {
        "port": 8888,
        "commandOutput": "append-at-end-on-error"
      },
      "dependencies": {
        "project-A": ["lib-1"],
        "project-B": ["lib-2"],
        "lib-1": [],
        "lib-2": []
      }
    },
    "build-some": {
      "dependencies": {
        "project-A": ["lib-1"],
        "project-B": ["lib-2"]
      }
    },
    "extended-scope": {
      "extends": "build-some",
      "dependencies": {
        "lib-1": ["lib-2"]
      }
    },
    "empty-deps": {
      "dependencies": {}
    }
  }
}
